### ISSUE TITLE
App icon appearing twice on phone screen

### ISSUE THREAD

**Issue by DigitalSeneca** [Mosquito-Alert/Mosquito-Alert-Mobile-App#111]
**Expected behavior**
It should appear only once

**Screenshots**
![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/346df1cd-c771-476e-a4ee-eb3920f25a7a)

**Smartphone (please complete the following information):**
Happened to multiple different users, but I only received device info about this
1:
 - Device: [Samsung A21s]
 - OS: [Android version 12,  One UI Core Version 4.1]
 - Version [e.g. 2.2.0+1717]

**Comment by epou** [comment]
Might be interesting: https://stackoverflow.com/questions/6028695/android-icon-been-duplicate-when-i-install-my-app-on-the-device
