### ISSUE TITLE
ANR: "There is only the white screen with the logo"

### ISSUE THREAD

**Issue by DigitalSeneca** [Mosquito-Alert/Mosquito-Alert-Mobile-App#112]
**Describe the bug**
"There is only the white screen with the logo. I tried to delete and re-install the app (several times), but the problem remains. And it is not just my phone, a colleague of mine had the same problem."

**Expected behavior**
It should open the app normally

**Smartphone (please complete the following information):**
Happened to multiple users
- Galaxy S10e, model number SM-G970F/DS. Android 12
- Galaxy S10, model number SM-G973F/DS. Android 12

Many users could not reproduce this bug on Android 9, 12, 13 and 14 -> They reported it's working normally for them

**Additional context**
It's probably the same error or related to [Google Developer Console: dalvik.system.BaseDexClassLoader.findClass](https://play.google.com/console/u/0/developers/6847921171114158955/app/4973233962343162851/vitals/crashes/db9355fa2f87e85199eb3ab58da965e3/details?days=28&versionCode=1717%2C1708&isUserPerceived=true)

**Comment by epou** [comment]
Links of interest:
- https://www.reddit.com/r/androiddev/comments/dwclxz/apk_crashing_when_downloading_from_playstore/
- https://www.reddit.com/r/androiddev/comments/bhp4bd/do_you_experience_the_following_crash_after/
- https://stackoverflow.com/questions/44278561/unexpected-crash-in-basedexclassloader/44325113#44325113

**Comment by DigitalSeneca** [comment]
I could reproduce the issue on emulator "Resizable API 34"

```
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install H:\Github\Mosquito-Alert-Mobile-App\build\app\outputs\flutter-apk\app-debug.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 1717 is older than current 1719]
Uninstalling old version...
D/FlutterGeolocator( 5165): Attaching Geolocator to activity
D/FlutterGeolocator( 5165): Creating service.
D/FlutterGeolocator( 5165): Binding to location service.
D/FlutterGeolocator( 5165): Geolocator foreground service connected
D/FlutterGeolocator( 5165): Initializing Geolocator services
D/FlutterGeolocator( 5165): Flutter engine connected. Connected engine count 1
```
![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/19e5a9cd-cbca-4cca-9124-1d04aa6cea7f)

**Comment by DigitalSeneca** [comment]
At the moment, the issue seems related to Proguard and use of non-SDK interfaces

The following 2 screenshots are reports that show a use of non-SDK interfaces of Ldalvik which are affecting 1064 users:

![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/1d82dc6b-22b1-485c-8843-b5d6ec34d50e)
![image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/7d35e8ac-b90d-42fb-bb97-f1701a8699f5)

**Comment by DigitalSeneca** [comment]
After version 1721 there are no more errors on Google Play Console related to this, but the issue is still happening as reported by some users.
All complaints were from users with language settings in German.
I changed my phone settings to "German - Austria", reinstalled the app and now it does not open, as described by the users
