### ISSUE TITLE
Improve Settings -> Autotag

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#134]
Complaints that the current way of adding and removing tags is not straightforward.

Here's my proposal for change:
Folded:
![autotag_folded](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/26668968/3a90e8fc-bbd3-4b6d-aa81-a7f5df735ef6)
Unfolded:
![autotag_unfolded](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/26668968/247bd1dc-0cd4-43e8-8f9e-7b3652a67296)

To take into consideration:
- badge counter should disappear when 0 (no tags added)

Interesting libraries: 
- https://pub.dev/packages/textfield_tags

**Comment by DigitalSeneca** [comment]
is there a limit on how many tags can there be? or the length of the string in the tag?
Right now only one hashtag can be added since it's a string in the code, and also in the API it expects to receive a string `"note": "string",`

Are we changing the frontend and api to de a list of strings, or should I do something like a single string "hashtag1,hashtag2,hashtag3" ?

**Comment by aescobarr** [comment]
> is there a limit on how many tags can there be? or the length of the string in the tag? Right now only one hashtag can be added since it's a string in the code, and also in the API it expects to receive a string `"note": "string",`
> 
> Are we changing the frontend and api to do a list of strings, or should I do something like a single string "hashtag1,hashtag2,hashtag3" ?

@DigitalSeneca there is no limit to the number of hashtags that could be assigned to one report. The limit is the size of the "notes" field on the report which is a PostgreSQL [text field](https://www.postgresql.org/docs/9.6/datatype-character.html). However, there seems to be a physical limit of [1Gb per column](https://wiki.postgresql.org/wiki/FAQ#What_is_the_maximum_size_for_a_row.2C_a_table.2C_and_a_database.3F).
