### ISSUE TITLE
Android crash: :com.google.android.gms.dynamite_mapsdynamite@231613044@23.16.13 (190400-0) - com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i

### ISSUE THREAD

**Issue by JohnPalmer** [Mosquito-Alert/Mosquito-Alert-Mobile-App#14]
Details at https://play.google.com/console/u/0/developers/6847921171114158955/app/4973233962343162851/vitals/crashes/9aa6f32d085ee808f929f9531538614c/details

**Comment by DigitalSeneca** [comment]
Right now the url does not seem to be working for me to show the impact in users to analyse it and diagnose a solution
