### ISSUE TITLE
Background tracking should be enbaled by default

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#175]
Source: https://docs.google.com/document/d/1D4bw4KXNMvdzJpSHLlMoI7x1V-5RKjSAfqDeJziir98/edit?disco=AAABQiA5Wb8

**Comment by DigitalSeneca** [comment]
I uninstalled the app and reinstalled it, and it appears enabled by default:

![Image](https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/assets/157690872/d8d5e585-465b-408a-8c49-83304e5399cd)

I also tried to disable background tracking > uninstall app > install app. In this case, it also appears enabled by default

**Comment by epou** [comment]
Okay, so then we can close this issue... Thanks for double-checking it @DigitalSeneca!
