### ISSUE TITLE
Auto-tagging menu behaviour

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#190]
When adding a new tag:
- When pressing 'enter' it remains saved but the Auto-Tagging menu folds. It should keep unfolded.
- When pressing on 'space bar', the tag appears in a new box but it is not saved (the counter does not change and when you fold and unfold the menu again it does not appear)

Users until now (schools) have been told that they should use '#' as a prefix, and now doing so appears two hashtags. Can this be avoided?

The button with the 'X' is gray, but it should be white (always the same color as text).

By default, if there is already a tag activated, the Auto-Tagging menu should appear unfolded.

When deleting a tag:
- It is expected that tags can be deleted using the 'delete' key on the keyboard.
- Clicking the 'X' button deletes the tag but closes the menu, it should not close.

**Comment by DigitalSeneca** [comment]
There are multiple subtopics in this ticket, so I'm dividing it so it's easier to handle and review:

When adding a new tag:
- [ ] When pressing 'enter' it remains saved but the Auto-Tagging menu folds. It should keep unfolded.
- [ ] When pressing on 'space bar', the tag appears in a new box but it is not saved (the counter does not change and when you fold and unfold the menu again it does not appear)

- [x] Users until now (schools) have been told that they should use '#' as a prefix, and now doing so appears two hashtags. Can this be avoided? -> #193 

- [x] The button with the 'X' is gray, but it should be white (always the same color as text). -> #194 

- [ ] By default, if there is already a tag activated, the Auto-Tagging menu should appear unfolded.

When deleting a tag:
- [ ] It is expected that tags can be deleted using the 'delete' key on the keyboard.
- [ ] Clicking the 'X' button deletes the tag but closes the menu, it should not close.
