### ISSUE TITLE
Data transmission issues and looping behavior

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#46]
The application encounters challenges in sending data, particularly in cases of a poor or non-existent connection. When there is no connectivity, the app enters a continuous loop attempting to transmit data without notifying the user of the issue. This persistent loop acts as a bottleneck, hindering the transmission of additional data to the server. Additionally, on mobile devices, if the app is not manually restarted after encountering this problem, it remains stuck in the loop, preventing further data submissions.

It's crucial to investigate and implement a technical solution to address this issue. It's also recommended to verify whether this problem is specific to iOS or if it extends to other platforms. A comprehensive review is necessary to ensure a robust and consistent user experience across all devices.

**Comment by epou** [comment]
Relates: #95

**Comment by DigitalSeneca** [comment]
> It's also recommended to verify whether this problem is specific to iOS or if it extends to other platforms.

I have not encountered this issue on Android in the last months so it's possible that it was already fixed or that it's only happening on iOS

**Comment by epou** [comment]
What happens when you try uploading a new report without having internet connection?

**Comment by DigitalSeneca** [comment]
It appears this message: "There was an error sending your report, but it is stored on your phone and will automatically be sent later"

**Comment by epou** [comment]
My suspicion is that this issue was related to the previously resolved bug that caused the spinner to display indefinitely. I'm closing this issue for now, but we can reopen it in the future if the problem reoccurs.
