### ISSUE TITLE
The "Settings -> Language" menu should order options alphabetically

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#68]
See: https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/blob/6c5993a230a86f958c8dca8bcfef2994a6b93ebe/lib/pages/settings_pages/settings_page.dart#L301-L334

**Comment by DigitalSeneca** [comment]
Alphabetically in English?

**Comment by epou** [comment]
Well, depending on the language selected for the user at that moment. For example, if the current language is Spanish, the list should display the names of the languages (in Spanish) alphabetically ordered.
