### ISSUE TITLE
Automatically add new translations from localise.biz using Github Actions

### ISSUE THREAD

**Issue by epou** [Mosquito-Alert/Mosquito-Alert-Mobile-App#69]
See: https://github.com/marketplace/actions/sync-translations-from-localise-biz

Ideally, it should open a new pull-request when detecting modification on the translations.
See: https://github.com/marketplace/actions/create-pull-request
(
PR_TITLE="Update Translations"
PR_BRANCH="update-translations-$(date +%s)"
PR_BODY="Automated pull request to update translations."
)

**Comment by DigitalSeneca** [comment]
What should be the target branch for those pull requests? Right now it's v33, but then it will be changing every x amount of time to v34, v35...
Should it be 'main'? It's always possible to manually update the target, but the more automation the better

**Comment by epou** [comment]
Yes, using 'main' is wiser for this kind of issue related to the repository workflow, and that does not add any change to the app itself.
