### ISSUE TITLE
Stop app from getting stuck while sending  reports

### ISSUE THREAD

**Issue by JohnPalmer** [Mosquito-Alert/Mosquito-Alert-Mobile-App#7]
We are getting increasing complaints of the app getting stuck when trying to send reports. Identify and fix the problem.

**Comment by epou** [comment]
Solved in:
https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/91
https://github.com/Mosquito-Alert/Mosquito-Alert-Mobile-App/pull/92
